### ISSUE TITLE
Did you use which version of Keras and Tensorflow?

### ISSUE THREAD

**Issue by eurismarpires** [justinsvegliato/deep-jammer#16]

**Comment by justinsvegliato** [comment]
To answer your question, we use Keras 1.0.3 and Theano 0.9.0 instead of TensorFlow. 

Having said that, we recommend using the purely Theano version of Deep Jammer since the Keras version trains slowly for some reason. We also haven't ran the Keras version in months, so we can't confirm that it's in a running state. We'll take care of that soon though! 

Check out the README that we wrote this morning. It should explain exactly how to use the Theano version. I hope that helps. I'm closing this for now since we've been chatting through email.
